// Generated by CoffeeScript 1.10.0
(function() {
  var Schema, argv, argvParser, env, file, parseSync, rJson, util;

  Schema = require('schemalet');

  argvParser = require('minimist');

  rJson = require('relaxed-json');

  util = require('./util');

  env = require('./env');

  argv = require('./argv');

  file = require('./file');

  parseSync = function(schemaSpec, options) {
    var argvVal, configVal, envVal, merge1, merge2, schema;
    if (options == null) {
      options = {};
    }
    options = {
      argv: options.hasOwnProperty('argv') ? options.argv : process.argv.slice(2),
      env: options.hasOwnProperty('env') ? options.env : process.env,
      rootPath: util.merge(file.defaultOpts.rootPath, options.rootPath),
      basePath: util.merge(file.defaultOpts.basePath, options.basePath),
      loadOrder: util.merge(file.defaultOpts.loadOrder, options.loadOrder),
      extMap: util.merge(file.defaultOpts.extMap, options.extMap)
    };
    schema = Schema.makeSchema(schemaSpec);
    configVal = file.loadSync(options);
    envVal = env.normalize(schema, options.env);
    argvVal = argv.normalize(schema, options.argv);
    console.log('configVal', configVal);
    console.log('envVal', envVal);
    console.log('argvVal', argvVal);
    merge1 = util.merge(configVal, envVal);
    merge2 = util.merge(merge1, argvVal);
    console.log('merged', merge2);
    return schema.convert(merge2);
  };

  module.exports = {
    parseSync: parseSync
  };

}).call(this);
