// Generated by CoffeeScript 1.10.0
(function() {
  var Schema, argv, argvParser, config, env, loader, rJson, util;

  Schema = require('schemalet');

  argvParser = require('minimist');

  rJson = require('relaxed-json');

  util = require('./util');

  loader = require('./loader');

  env = require('./env');

  argv = require('./argv');

  config = function(schemaSpec) {
    var argvVal, configVal, envVal, schema;
    schema = Schema.makeSchema(schemaSpec);
    configVal = loader.loadSync();
    envVal = env.getEnvVars(schema);
    argvVal = argv.getArgvVars(schema);
    return schema.convert(util.merge(argvVal, envVal, configVal));
  };

  module.exports = {
    config: config
  };

}).call(this);
